apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dotnet-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dotnet
spec:
  hosts:
  - "*"
  gateways:
  - dotnet-gateway
  http:
  - route:
    - destination:
        host: dotnet
